### PR TITLE
Fix Contact definition fix #66

### LINKED ISSUE #66: Exception in getUpdates: Unexpected ASDF kind
Stacktrace:
```
Failed processing updates: asdf.serialization.DeserializationException@../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d(2248): Unexpected ASDF kind
----------------
??:? [0x560372381305]
??:? [0x5603723a74a6]
??:? [0x56037238bc0d]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2248 [0x5603721702f5]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2606 [0x56037219a207]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2771 [0x5603721a5c1e]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2606 [0x56037219ada1]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2771 [0x5603721995da]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2606 [0x560372198755]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2771 [0x56037219826c]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2345 [0x560372197cc1]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:2771 [0x5603721978b9]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:459 [0x560372194c71]
app/../../.dub/packages/asdf-0.5.7/asdf/source/asdf/serialization.d:508 [0x56037218f173]
botapi.d:224 [0x56037218ee3e]
basic.d:1106 [0x5603721adfe9]
app/source/app.d:173 [0x56037215a2e1]
app/../../.dub/packages/vibe-core-1.9.3/vibe-core/source/vibe/core/task.d:702 [0x56037215d787]
task.d:720 [0x560372306d61]
task.d:426 [0x56037230654d]
??:? [0x560372382408]
```

To reproduce, send a message with a reply keyboard button requesting contact information and click it in the app:

```d
SendMessageMethod msg;
msg.chat_id = state.chat;
msg.text = "Hello world";
ReplyKeyboardMarkup keyboard;
keyboard.one_time_keyboard = true;
keyboard.keyboard = [[KeyboardButton("click me to break", true)]];
msg.reply_markup = keyboard;
bot.sendMessage(msg);
```

Updates response message:
```json
{
    "ok": true,
    "result": [
        {
            "update_id": 123456789,
            "message": {
                "message_id": 4,
                "from": {
                    "id": 987654321,
                    "is_bot": false,
                    "first_name": "Bob",
                    "username": "john_doe123",
                    "language_code": "de"
                },
                "chat": {
                    "id": 987654321,
                    "first_name": "Bob",
                    "username": "john_doe123",
                    "type": "private"
                },
                "date": 1596628967,
                "contact": {
                    "phone_number": "4912345678912",
                    "first_name": "Bob",
                    "user_id": 987654321
                }
            }
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by WebFreak001**
See https://core.telegram.org/bots/api#contact

### CODE REVIEW

File: source/telega/telegram/basic.d [hunk 1]
```diff
@@ -319,7 +319,7 @@ struct Contact
     string phone_number;
     string first_name;
     Nullable!string last_name;
-    Nullable!string user_id;
+    Nullable!long user_id;
```
Comment (nexor) [inline source/telega/telegram/basic.d:322]:
```suggestion
    Nullable!uint user_id;
```
AFAIK user ID is not bigger than 32 bit unsigned, so this library uses uint everywhere

**Comment by nexor** [comment]
Thank you!
